### ISSUE TITLE
If a rectangle has the same size as one bin it's packed into a bigger bin 

### ISSUE THREAD

**Issue by BeAntares** [secnot/rectpack#9]
I have a set of bins, some of them have the same size as some rectangles, and I need to use the same size bins, but the default algorithm chooses a bigger bin for that rectangle. Is it a feature? Is there a parameter to avoid that?

**Comment by secnot** [comment]
Hi

If the rectangles and the bins have the same size or nearly the same size it should be easier and faster to find them and then pack the remaining rectangles with rectpack.

If that isn't possible it could probably be done with rectpack by sorting the bins in ascending order by area, the rectangles by descending order, and use one of the algorithms for best area fit (Baf), with online packing, or offline BFF.  

The problem is that all the algorithms used by rectpack are heuristic, and if you find the combination that packs correctly those rectangles, the packing for the remainig rectangles would almost certainly be very bad.

I would use the first approach specially if the sizes for the pairs are exactly the same.

**Comment by BeAntares** [comment]
Thanks @secnot, how can I sort the bins in ascending order? From the documentation I see the rectangles can be sorted using the sort_algo=SORT_AREA parameter but I can't find a parameter to sort the bins, should I provide the sorted bins to the packer? 
I'll try the first approach.

**Comment by BeAntares** [comment]
I'm sorry, the optimization was right, I made a mistake plotting the rectangles inside the bins. It works great.
